package.json
Otherwise it only looks in the .js files!!
=> Include .vue filetype in `$ npm run lint`

src/api/Recording.api.js, src/api/Recording.api.test.js, src/api/Tag.api.test.js, src/components/QueryRecordings/QueryRecordings.vue, src/views/RecordingsView.vue, src/views/VideoView.vue
I've written a simple test for recording.api.test in a similar fashion to user.api.test. 
However, I'm not quite sure what's actually happening or what the point of the test is.... is it actually calling the API or only some mock version? What does the mock do? What sort of errors will this detect?
I stopped when I realised that lines 26 and 45 were going to require me to implement exactly the same procedure as in the actual code, which I thought was to be avoided in tests...
@adbs1 ?
=> Add tests for recording.api and tag.api

src/api/User.api.js, src/api/fetch.js, src/router/index.js, src/stores/modules/User.store.js, src/views/AddEmailView.vue, src/views/RegisterView.vue
- Registering now requires an email.
- Users that don't have an email will be redirected to a page to get there email.
=> Add user email requirement

src/components/TableRecordings.vue, src/fontAwesomeIcons.js, src/views/RecordingsView.vue
=> Show battery status in recordings query table

package-lock.json, package.json
As detected by Github.
https://nvd.nist.gov/vuln/detail/CVE-2018-14041
=> Update bootstrap to address potential security issue

src/components/Video/ObservedAnimals.vue, src/components/Video/QuickTag.vue, src/fontAwesomeIcons.js, src/views/RecordingView.vue
=> Add confirm automatic tag button

src/components/QueryRecordings/QueryRecordings.vue, src/components/QueryRecordings/SelectDevice.vue
Closes #26
Please check this works with more than the handful of devices I have available!
=> Add select by device group

src/main.js
Fixes #73 
Improved alternative to #74
=> Simpler fix for fontawesome layers component registration

src/components/BatteryLevel.vue, src/components/TableRecordings.vue, src/components/Video/VideoProperties.vue, src/fontAwesomeIcons.js, src/views/RecordingView.vue
Closes #37
- Add recording properties similar to old UI
- Plus improve battery icon on query recordings table
- Display of 'Relative to Dusk/Dawn' could be improved -> I wasn't sure what units were here
I only have a limited set of recordings to look at so once again please let me know if anything odd comes up!
=> Add properties to view recording screen

src/stores/modules/User.store.js
=> Store recordingTypePref in localStorage for persistance between sessions

.travis.yml, README.md, nfpm.yaml, package-lock.json, package.json
Release debs will be automatically created for any tag that is pushed to Github. This should speed up the release process and reduce the scope for human error.
=> Set up TravisCI to build releases 

src/views/RecordingView.vue
This had broken the view recording screen.
=> Put missing :recording attribute back in

src/components/Video/PrevNext.vue, src/components/Video/VideoHelp.vue, src/fontAwesomeIcons.js, src/main.js
Update of https://github.com/TheCacophonyProject/cacophony-web-vuex/pull/79 to fix icons opacity.
=> Fix prev next button layout

README.md, package-lock.json, src/api/Device.api.js, src/api/Device.api.test.js, src/api/Groups.api.js, src/api/Groups.api.test.js, src/components/Devices/DeviceAddUser.vue, src/components/Devices/DeviceDetail.vue, src/components/Groups/GroupDetail.vue, src/components/Groups/GroupUserAdd.vue, src/stores/modules/Devices.store.js, src/stores/modules/Devices.store.test.js, src/stores/modules/Groups.store.js, src/stores/modules/Groups.store.test.js
This requires the new api changes.   Devices users to come...
=> Add user should now work with username

src/stores/modules/Video.store.js
Need to wait for this to land https://github.com/TheCacophonyProject/cacophony-api/pull/153
Fixes #86
=> Use username instead of userId in tag info

package-lock.json, src/components/Devices/DeviceDetail.vue, src/components/Devices/DeviceListing.vue, src/components/GlobalMessaging.vue, src/components/Groups/GroupAdd.vue, src/components/Groups/GroupDetail.vue, src/components/Groups/GroupListing.vue, src/components/IconLink.vue, src/fontAwesomeIcons.js, src/stores/modules/Groups.store.js, src/stores/modules/Groups.store.test.js, src/views/DeviceView.vue, src/views/GroupView.vue, src/views/HomeView.vue
- link on the home page for creating a new group
- instructions on what to call group
- proper handling if group already exists. 
- nicer error messages.
=> Improve cacophonometer user-experience

src/components/QueryRecordings/QueryRecordings.vue
=> Add time to toDate query to include the day not stop at 00:00hrs

src/api/User.api.js, src/components/Groups/GroupDetail.vue, src/stores/modules/User.store.js
Will now see the 'Add users' in group view when a superuser added to a group not as an admin.
=> Handle global permissions

src/components/NavBar.vue, src/views/RecordingView.vue
- Change settings to 'Admin'  Closes #111
- Changed greeting alignment to centre to increase separation from the Admin dropdown
- Hide greeting on collapsed menu
- Add padding to Admin to align it correctly on collapsed menu
- Fix signedUrl?jwt=null error closes #101
=> Bug fixing

src/components/TableRecordings.vue, src/views/RecordingsView.vue
=> Add colour to tag output

src/components/Video/TrackData.vue, src/components/Video/VideoProperties.vue, src/fontAwesomeIcons.js
Displays the track data under the additional metadata.   It has an arrow to open up.
=> Display track data

package-lock.json, package.json
https://nvd.nist.gov/vuln/detail/CVE-2018-14732
=> Bump webpack-dev-server dependency

src/stores/modules/Video.store.js
This will hide the tags that don't have a user and allow the page to load normally.
=> Video will still load if a tagger doesn't have a user

package-lock.json, src/components/QueryRecordings/QueryRecordings.vue, src/components/QueryRecordings/SelectDuration.vue
closes #136 
This seems to be a Firefox bug because it was working for me on Chrome. Hopefully working in both now!
=> Add event to function parameters

src/views/RecordingsView.vue
An easy one to get the ball rolling! Closes #148 if you're happy @saracoutinho
=> Fix pagination to the bottom of the page inside white footer bar

src/components/NavBar.vue, src/fontAwesomeIcons.js
I don't know how often I'll be able to contribute - so it might be little chunks like this -> steps toward #143 and others. In this case removing the green from the nav and adding the appropriate font awesome icons.
=> Change navbar style to match new UI

src/components/Video/AddCustomTrackTag.vue, src/components/Video/AddObservation.vue, src/components/Video/PrevNext.vue, src/components/Video/Track.vue, src/components/Video/VideoRecording.vue
- new track tags,
-  new recording tags (eg missed track) 
- improved layout on phones and very very small screens.
=> A few small improvements for track tagging 

package.json, src/components/Video/VideoRecording.vue, src/views/RecordingsView.vue
The recordings page should now work on IPad, 
Small fix so that when you swap videos you always start with track 1. 
also...
Added new run mode dev:publish for when you want to test on other devices in your network.
=> Fixes for release

src/components/QueryRecordings/QueryRecordings.vue, src/components/Video/PrevNext.vue, src/views/RecordingsView.vue
1.   if final date field is set and cleared, it now works.  
2.  No longer send tags unless a tag is selected (should be fixed on api as well)
3.  Fix next/previous buttons for interesting recording
=> Three fixes - 

src/components/Video/ThermalVideoPlayer.vue
fixes video track overlay being offset incorrectly
=> renamed css class

src/components/Video/TrackTags.vue
=> Work around flickering Confirm Tag popover

package-lock.json, package.json
https://npmjs.com/advisories/1065
=> Address lodash vulnerability

src/api/Recording.api.js, src/api/User.api.js, src/components/QueryRecordings/CsvDownload.vue, src/components/Video/RecordingProperties.vue, src/views/RecordingsView.vue
=> Add a CSV export button to the recordings query screen

src/components/Video/RecordingControls.vue, src/const.js
=> Add trap buttons to video recording screen

src/stores/modules/Video.store.js
This PR contains a number of optimisations of to state updates for recording tags and track tags. By being more precise in the updates made various page refreshes are avoided and UI feedback latency is reduced.
Fixes #178.
=> Avoid unnecessary page refreshes on recordings screen

package-lock.json, src/components/Video/QuickTagTrack.vue, src/components/Video/RecordingControls.vue, src/components/Video/RecordingProperties.vue, src/components/Video/Track.vue, src/components/Video/TrackData.vue, src/components/Video/TrackTags.vue, src/components/Video/VideoRecording.vue, src/styles/global.css, src/views/RecordingView.vue
Style/markup changes to make this page look better.
=> General tidy up of the video recording page

src/components/QueryRecordings/CsvDownload.vue, src/views/RecordingsView.vue
Small tweaks to the recordings page:
- Show who tagged on hover (human or AI). Can be extended later on to show user name
- Have a "no results" placeholder when there are no results
- Small style tweak to the export button
Closes #211
=> Recordings search: additional changes

src/components/RecordingSummary.vue, src/views/RecordingsView.vue
=> Minor tweaks to the table view of the recordings

.eslintignore, .eslintrc.js, src/components/Analysis/DeviceGroups.vue, src/components/Devices/DeviceDetail.vue, src/components/Groups/GroupDetail.vue, src/components/HomeGroupItem.vue, src/components/QueryRecordings/CsvDownload.vue, src/components/QueryRecordings/QueryRecordings.vue, src/components/QueryRecordings/SelectDateRange.vue, src/components/QueryRecordings/SelectDevice.vue, src/components/QueryRecordings/SelectDuration.vue, src/components/Video/AudioRecording.vue, src/components/Video/RecordingControls.vue, src/components/Video/RecordingProperties.vue, src/components/Video/Track.vue, src/components/Video/TrackTags.vue, src/components/Video/VideoRecording.vue, src/views/AnalysisView.vue, src/views/RecordingsView.vue
removed eslint rule that was breaking prettier
=> fixed lint

package-lock.json, src/components/QueryRecordings/QueryRecordings.vue, src/components/QueryRecordings/SelectDuration.vue, src/views/RecordingsView.vue
Note that this will probably fail CI, since it looks like prettier is at odds with eslint in terms of some indentation rules inside of expressions inside string interpolations :-(
=> Fixes #235, #234, #230, #224, and #223

src/components/Video/AudioRecording.vue, src/components/Video/ThermalVideoPlayer.vue
also fixed bug where clicking previous recordings chagnes playback rate to 1 for videos
=> added delete to audio recordings

src/components/Video/AudioRecording.vue
Make done go to next recording
=> changed done to get next recording

src/api/Recording.api.js, src/components/TagBadge.vue, src/components/Video/QuickTagTrack.vue, src/components/Video/Track.vue, src/components/Video/TrackTags.vue, src/stores/modules/Video.store.js, src/styles/_tag-colours.scss, src/styles/global.css
added constant tag colours, to use consistently accross site.
Relies upon api PR https://github.com/TheCacophonyProject/cacophony-api/pull/272
=> Updated tags to use replaceTag endpoint

src/api/User.api.js, src/api/User.api.test.js, src/router/index.js, src/stores/modules/User.store.js, src/views/EndUserAgreementView.vue, src/views/RegisterView.vue
- Users now need to accept the end user agreement to register
- If the uses has not accepted the latest EUA they will be redirected to accept it.
- API PR to add EUA https://github.com/TheCacophonyProject/cacophony-api/pull/282
=> Added eua page

src/components/Video/ThermalVideoPlayer.vue
dont use computed html player to bind rate change as it seems to be stale
=> fix playback rate

src/components/Video/ThermalVideoPlayer.vue
canvas and tracks.
That was stupid, I think I just happened to test on a video without any tracks.
Third time lucky?
=> In mount hook, make sure player is initialised *before* overlay

README.md, src/views/VisitsView.vue
had extra cell word which wasn't needed
=> removed cell from slot

src/components/Chart/BarChart.vue, src/views/AnalysisView.vue
This is to fix the problem where it sometimes seems to overload the server if we try and run as an administrator.   It will now only run when you select a group.
=> Analysis only runs when you select a group

package-lock.json, package.json, src/components/QueryRecordings/CsvDownload.vue, src/components/QueryRecordings/QueryRecordings.vue, src/components/RecordingSummary.vue, src/components/Video/VideoRecording.vue, src/views/AnalysisView.vue, src/views/RecordingsView.vue, src/views/VisitsView.vue
Visits no query on page load, 
Recordings table view has correct link
Recordings table view order of columns changed
Fixed recordings next/prev bug
Default search period is 7 days. 
Fixed export problems
=> Visits don't make request on page load and other fixes

package.json
=> Bump cptv-player-vue version to fixed.

package.json, src/api/Recording.api.ts, src/components/NavBar.vue, src/components/Video/VideoRecording.vue
Fixes recording query having from date stripped out, and pulls in changes to fix seeking to first frame of tracks in player
=> Pre release fixes
