nfpm.yaml, package-lock.json, package.json, src/components/QueryRecordings/QueryRecordings.vue, src/components/TableRecordings.vue, src/components/Video/PrevNext.vue, src/components/Video/QuickTag.vue, src/components/Video/VideoProperties.vue, src/fontAwesomeIcons.js, src/router/index.js, src/views/RecordingView.vue, src/views/RecordingsView.vue, src/views/VideoView.vue
- swap date and time columns on recordings query results table
- default to 300 recordings per page (requested by Grant)
- Show recording type as icon
- Remove unnecessary text from recording view
- Rename VideoView to RecordingView and adjust routes
- Use <audio> for playing audio
- Make video player take up full width
- Fix size and alignment of prev/next & tag buttons
Fixes #32. Also deals with much of #18.
=> Improve support for audio recordings

src/components/QueryRecordings/QueryRecordings.vue, src/components/QueryRecordings/SelectDuration.vue, src/components/QueryRecordings/SelectRecordingType.vue, src/components/QueryRecordings/SelectTagTypes.vue
Closes #18 
Should be merged after #61 because I didn't manage my branches too well in my fork sorry! It's really only the last commit that is different here.
=> Allow filter by recording type in search recording screen

src/components/QueryRecordings/QueryRecordings.vue, src/components/QueryRecordings/SelectAnimal.vue, src/components/QueryRecordings/SelectTagTypes.vue, src/stores/modules/User.store.js
Closes #65 and partially #64 
Will remember preference within a single session but does not currently store between sessions
Provides tooltip to explain why those fields are disabled
Resets fields to default when recording type includes audio (to prevent those fields being included in the query)
=> Disable tag types and animal input when recording type includes audio

src/components/Video/PrevNext.vue, src/components/Video/VideoHelp.vue, src/fontAwesomeIcons.js, src/main.js
Since the FontAwesomeLayers import fix the layout of the prev/next
buttons has been messed up. It turns out the correct layout is
achieved by not using `font-awesome-layers` at all!
=> Fix up prev/next buttons

src/views/RecordingView.vue
tags info was being added to the `where` parameter when they should be there own parameter.
=> Fixed recordings tags param

src/views/RecordingView.vue
When the page first loads, the recordings details are not loaded so you would get `recording.Device is null` error in the console.
Fixes #95
=> Will not get devicename if there is no recording.

index.template.ejs
closes #102 I hope - although I haven't been able to test on all devices/browsers
=> Add / to href paths in index.template.ejs to avoid favicon path errors

src/components/Video/VideoProperties.vue
When values like `airplaneModeOn` in the metadata was false they would not be shown. This should fix that.
=> Will only hide metadata that is null

src/components/QueryRecordings/QueryRecordings.vue
The guard for the query in the `mounted` handler was not complete
meaning there were errors reported every time the page loaded.
The empty object is now checked for correctly and there specific
guards for each query field in case any field is missing.
Also changed behaviour so that a query is always automatically
performed on page load as this has been requested before.
=> Fix errors in query recordings mounted handler

src/api/fetch.js, src/api/fetch.test.js, src/components/HomeGroupItem.vue, src/components/Video/RecordingProperties.vue, src/stores/modules/Devices.store.js, src/stores/modules/Devices.store.test.js, src/stores/modules/Groups.store.js, src/stores/modules/Groups.store.test.js, src/stores/modules/User.store.js, src/stores/modules/Video.store.js, src/views/AnalysisView.vue, src/views/RecordingsView.vue
Fixes #14
Can use object destructuring to have little clutter from the code and allows easy extension of the fetch API in the future if we need to return more information from the response
=> Refactored fetch API to return an object rather than the response body only fix #14

src/components/Audio/TagList.vue, src/components/Help.vue, src/components/Video/ObservedAnimals.vue, src/components/Video/PrevNext.vue, src/components/Video/TrackTags.vue
- make track tag tooltips display on the right to avoid flickering and
- inaccessible buttons (fixes #185)
- switch from v-b-popover to v-b-tooltip throughout as these are more
appropriate and have better contrast
- use v-b-tooltip instead of titles for prev/next recording buttons
(for consistency)
=> Workaround for tooltip positioning issues

src/components/Audio/TagList.vue, src/components/Help.vue, src/components/Video/AddCustomTrackTag.vue, src/components/Video/ObservedAnimals.vue, src/components/Video/PrevNext.vue, src/components/Video/QuickTagTrack.vue, src/components/Video/Track.vue, src/components/Video/TrackTags.vue
Use a fixed id for the modal so that it continues to work when moving between recordings. Fixes #184.
Also: Apply "hover" to all tooltips. The default is "hover focus" and "focus" means the tooltip can stay up if a button or icon is pushed.
=> Fix "other..." tag modal only working for first recording 

src/components/Video/RecordingControls.vue, src/components/Video/VideoRecording.vue
These were being hidden on mobile but actually work fine when shown.
Hide the exclaimation point icon on smaller displays to create some
more space.
=> Show global recording buttons on small screens too

src/components/Video/Comment.vue, src/components/Video/RecordingControls.vue, src/components/Video/VideoRecording.vue, src/stores/modules/Video.store.js
A new Comment button has been added which pops up a modal which shows
the current comment and allows it to be updated. Comment updates are
pushed through the store (the previous implementation made a direct
API request).
Four buttons on a single row didn't render well on mobile so the
buttons now spread over two rows on smaller screens.
=> Restore recording comment functionality

src/components/Video/Track.vue
At a certain size only one track was visible and there was no way of navigating between tracks (arrows were hidden)
=> Fix video tracks not displaying at a certain size (tablet-ish)

src/api/User.api.js
Intended for CacophonyApi.patch to receive the exact object as passed into updateFields,
for example if updateFields given:
`{ email: "mail@jacksteel.co.nz" }`
It should pass that to PATCH body.
Instead, it was incorrectly wrapping it into a fields object, meaning the PATCH body looked like
`{ fields : { email: "mail@jacksteel.co.nz" } }`
Which isn't what it should be and isn't what the server expects, meaning PATCH requests were failing.
I've gone through and done more testing for any other endpoints that had any semantic changes and am pretty confident this is the only issue.
=> Fix bug where fields to update were being wrapped in a fields object

src/components/Video/RecordingControls.vue
These offer little value and often get in the way preventing access to the buttons.
=> Remove tooltips on for recording buttons

src/components/Video/VideoTracksScrubber.vue
Fixes scrubber track offsetting issues, and also tweaks the way that the padding is applied to line up to the video player UI.  Previously the playhead/position overlay was pushed in, which created an ugly gap at the beginning and end of the scrubber where it was a lighter colour gray.
=> Tweak scrubber offsetting and fix css offset issue.

src/components/QueryRecordings/QueryRecordings.vue
specifically when date time parameter of all was selected, if you releoaded the page it would get stuck on loading...
this occured because the route remained the same and we were only firing the submit event when the $route watch event fired.
while with a relative date, the seconds changed (since initial load) and hence $route changed and we get the event load recordings
=> fixed bug with page not loading for some urls

src/api/Recording.api.ts
It might be null or undefined - support both.
=> Don't send deviceId to /needs-tag if it is null

src/components/Video/ThermalVideoPlayer.vue, src/views/TaggingView.vue
- Change position of action buttons to have less white space
in cases where there aren't many tracks
- Handle video player load errors by requesting the next
video if loading fails.
- Don't load dummy recording src on load, this results in an error.
=> - Add tagger delete recording button for globalWrite users

src/components/Video/ThermalVideoPlayer.vue, src/views/RecordingView.vue
on watched variables changing to set the video initially.
(Previously the video player relied on a dummy src url being set to trigger a Vue watcher to initialise the url of the player, but this caused a video js error in the console, as the player couldn't load the dummy url - it's better to initialise those sorts of things inside the component mount hook)
=> Try to set the video url on mount, rather than relying

src/components/GlobalMessaging.vue
- Alert banner stretches 100% width now (before it had a gap on the right)
- Removed 100000px attempt 
- Removed classes that were causing this conflict in styling
- Added small left padding to give error text a bit of breathing space - if you want it centred or something else feel free to let me know!
=> Alert banner full width, added padding to text

src/api/Groups.api.ts, src/api/Recording.api.ts, src/components/Groups/DevicesTab.vue, src/components/Groups/StationsTab.vue, src/components/Groups/UsersTab.vue, src/views/GroupView.vue
This PR goes with https://github.com/TheCacophonyProject/cacophony-api/pull/355 for the api changes.
- Only show active devices in device listings in the UI
- Nicer feedback when adding stations and matching recordings
- Fix delete user issue.
- Use simplified get APIs for listing group devices and group users (no longer all together)
=> Only active devices

package.json, src/components/NavBar.vue
Realised that top revision info banner wasn't checking the correct variable, and would have shown up on prod
=> Fix navbar message
